"""RCA (Root Cause Analysis) entity."""

from dataclasses import dataclass, field
from typing import Any

from src.domain.entities.classification import Classification, FailureCategory, Severity


@dataclass
class RCA:
    """Domain entity representing a Root Cause Analysis result.
    
    Single Responsibility: Only holds RCA data and formatting.
    """
    
    classification: Classification
    root_cause: str
    evidence_summary: str
    
    # Optional code analysis fields
    github_url: str = ""
    test_file: str = ""
    code_analysis: str = ""
    fixtures: list[str] = field(default_factory=list)
    
    @property
    def category(self) -> FailureCategory:
        """Get classification category."""
        return self.classification.category
    
    @property
    def confidence(self) -> float:
        """Get classification confidence."""
        return self.classification.confidence
    
    @property
    def severity(self) -> Severity:
        """Get classification severity."""
        return self.classification.severity
    
    @property
    def reasoning(self) -> str:
        """Get classification reasoning."""
        return self.classification.reasoning
    
    @property
    def recommendation(self) -> str:
        """Get classification recommendation."""
        return self.classification.recommendation
    
    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "classification": self.classification.category.value,
            "confidence": self.classification.confidence,
            "severity": self.classification.severity.value,
            "root_cause": self.root_cause,
            "reasoning": self.classification.reasoning,
            "evidence_summary": self.evidence_summary,
            "recommendation": self.classification.recommendation,
            "github_url": self.github_url,
            "test_file": self.test_file,
            "code_analysis": self.code_analysis,
            "fixtures": self.fixtures,
        }
    
    def to_rp_comment(self) -> str:
        """Format RCA as ReportPortal comment with AI marker."""
        icon = self.classification.category.icon
        sev_icon = self.classification.severity.icon
        
        comment = f"""## {icon} AI Classification: {self.classification.category.value}

**Confidence:** {self.classification.confidence_percent}%
**Severity:** {sev_icon} {self.classification.severity.value}

### Root Cause
{self.root_cause}

### Why This Classification
{self.classification.reasoning}

### Evidence
{self.evidence_summary}
"""
        
        # Add code analysis section if available
        if self.code_analysis:
            comment += f"""
### Code Analysis
{self.code_analysis}
"""
        
        # Add fixtures if present
        if self.fixtures:
            comment += f"""
**Fixtures used:** {', '.join(self.fixtures[:5])}
"""
        
        # Add GitHub link if available
        if self.github_url:
            comment += f"""
**Test Source:** [{self.test_file or 'View on GitHub'}]({self.github_url})
"""
        
        comment += f"""
### Recommendation
{self.classification.recommendation}

---
*🤖 AI: Generated by TFA (Thinker-Critic Pattern)*
"""
        return comment

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "RCA":
        """Create RCA from dictionary."""
        classification = Classification(
            category=FailureCategory.from_string(data.get("classification", "To Investigate")),
            confidence=data.get("confidence", 0.5),
            severity=Severity(data.get("severity", "MEDIUM").upper()),
            reasoning=data.get("reasoning", ""),
            recommendation=data.get("recommendation", ""),
        )
        return cls(
            classification=classification,
            root_cause=data.get("root_cause", ""),
            evidence_summary=data.get("evidence_summary", ""),
            github_url=data.get("github_url", ""),
            test_file=data.get("test_file", ""),
            code_analysis=data.get("code_analysis", ""),
            fixtures=data.get("fixtures", []),
        )
