"""RCA Investigator using Thinker-Critic pattern with LLM reasoning.

DEPRECATED: This module is maintained for backward compatibility.
For new code, use:
    - src.application.use_cases.investigate_rca.InvestigateRCAUseCase
    - src.domain.services.investigation_service.InvestigationService
    - src.domain.entities.rca.RCA
"""

import asyncio
import re
import hashlib
import warnings
from dataclasses import dataclass, field
from typing import Any

from src.llm.base import LLMProvider
from src.utils.logging import get_logger

logger = get_logger(__name__)

# Emit deprecation warning on first use
warnings.warn(
    "src.investigator is deprecated. Use src.application.use_cases.investigate_rca instead.",
    DeprecationWarning,
    stacklevel=2,
)

# RHOAI Domain Knowledge
RHOAI_CONTEXT = """
RHOAI/ODH Component Knowledge:
- KServe: Serverless inference platform for ML models
- InferenceService: KServe CRD for deploying models
- vLLM: High-performance LLM inference runtime (GPU-optimized)
- Kueue: Kubernetes batch scheduler for ML workloads
- ResourceFlavor: Kueue CRD defining compute resources
- ModelMesh: Multi-model serving infrastructure
- TrustyAI: Model explainability service
- Codeflare: Distributed computing for ML
- Ray: Distributed execution framework

Common Failure Patterns:
- CRD not found → Operator not installed or needs reconciliation
- InferenceService not ready → Model loading, resource constraints, or config error
- Timeout waiting for pod → Resource scheduling, image pull, or init container issues
- OOMKilled → Memory limit too low for model size
- GPU unavailable → Node selector, taint, or quota issues
"""


@dataclass
class Evidence:
    """Evidence collected from logs and code."""
    error_message: str = ""
    error_type: str = ""
    patterns: list[str] = field(default_factory=list)
    test_code: str = ""
    test_file: str = ""
    fixtures: list[str] = field(default_factory=list)
    decorators: list[str] = field(default_factory=list)
    stack_trace: str = ""
    verification_result: str = "not_run"
    verification_output: str = ""
    historical_failures: int = 0
    historical_pass_rate: float = 1.0
    known_flaky: bool = False


@dataclass
class RCA:
    """Root Cause Analysis result."""
    classification: str
    confidence: float
    root_cause: str
    reasoning: str
    evidence_summary: str
    recommendation: str
    severity: str = "MEDIUM"
    # Code fetcher fields (optional)
    github_url: str = ""
    test_file: str = ""
    code_analysis: str = ""
    fixtures: list[str] = field(default_factory=list)
    
    def to_dict(self) -> dict[str, Any]:
        return {
            "classification": self.classification,
            "confidence": self.confidence,
            "root_cause": self.root_cause,
            "reasoning": self.reasoning,
            "evidence_summary": self.evidence_summary,
            "recommendation": self.recommendation,
            "severity": self.severity,
            "github_url": self.github_url,
            "test_file": self.test_file,
            "code_analysis": self.code_analysis,
            "fixtures": self.fixtures,
        }
    
    def to_rp_comment(self) -> str:
        icon = {
            "Product Bug": "🐛",
            "Test Automation Issue": "🔧",
            "Infrastructure Issue": "🌐",
            "Intermittent Failure": "🔄",
        }.get(self.classification, "❓")
        
        comment = f"""## {icon} AI Classification: {self.classification}

**Confidence:** {self.confidence * 100:.0f}%
**Severity:** {self.severity}

### Root Cause
{self.root_cause}

### Why This Classification
{self.reasoning}

### Evidence
{self.evidence_summary}
"""
        
        # Add code analysis if available
        if self.code_analysis:
            comment += f"""
### Code Analysis
{self.code_analysis}
"""
        
        # Add fixtures if present
        if self.fixtures:
            comment += f"""
**Fixtures used:** {', '.join(self.fixtures[:5])}
"""
        
        # Add GitHub link if available
        if self.github_url:
            comment += f"""
**Test Source:** [{self.test_file or 'View on GitHub'}]({self.github_url})
"""
        
        comment += f"""
### Recommendation
{self.recommendation}

---
*🤖 AI: Generated by TFA (Thinker-Critic Pattern)*
"""
        return comment


DEFINITIVE_PATTERNS = [
    (r"CrashLoopBackOff|ImagePullBackOff|OOMKilled", "Infrastructure Issue", "Pod failure", 0.95),
    (r"AccessDenied|InvalidAccessKeyId|SignatureDoesNotMatch", "Infrastructure Issue", "AWS credentials", 0.95),
    (r"connection.*refused|connection.*reset|network.*unreachable", "Infrastructure Issue", "Network", 0.90),
    (r"TimeoutExpiredError|TimeoutSampler.*expired|Timed Out", "Test Automation Issue", "Timeout", 0.80),
    (r"AssertionError|assert.*failed", "Test Automation Issue", "Assertion", 0.75),
    (r"fixture.*not.*found|SetupError", "Test Automation Issue", "Fixture error", 0.90),
    (r"InferenceService.*Failed|InferenceService.*not.*[Rr]eady", "Product Bug", "Service failure", 0.70),
    (r"CRD.*not.*found|Couldn't find.*in.*api.*group", "Infrastructure Issue", "CRD missing", 0.90),
    (r"Internal.*[Ss]erver.*[Ee]rror|status.*code.*5[0-9]{2}", "Product Bug", "Server error", 0.80),
    (r"CUDA.*error|GPU.*not.*available|nvidia.*driver", "Infrastructure Issue", "GPU issue", 0.95),
    (r"ResourceQuota.*exceeded|quota.*exceeded", "Infrastructure Issue", "Quota exceeded", 0.95),
    (r"PodScheduled.*False|Unschedulable", "Infrastructure Issue", "Scheduling", 0.90),
]

FLAKY_INDICATORS = [
    r"@pytest\.mark\.flaky",
    r"@pytest\.mark\.xfail",
    r"@retry",
    r"flaky_test",
    r"random\.",
    r"time\.sleep",
    r"wait_for.*timeout",
]


class RCAInvestigator:
    """Investigates test failures using Thinker-Critic LLM pattern."""
    
    def __init__(
        self,
        llm_provider: LLMProvider | None = None,
        history_store=None,
        progress_callback=None,
    ):
        self.llm = llm_provider
        self.history_store = history_store
        self.progress_callback = progress_callback
        self._verified_signatures: dict[str, str] = {}
    
    def _report_progress(self, step: str, detail: str = ""):
        if self.progress_callback:
            self.progress_callback(step, detail)
        logger.debug("progress", step=step, detail=detail[:50] if detail else "")
    
    async def investigate(
        self,
        test_name: str,
        logs: str,
        test_code: str = "",
        verification_result: str = "not_run",
        verification_output: str = "",
    ) -> RCA:
        """Investigate a test failure with full reasoning pipeline."""
        self._report_progress("gathering", "Collecting evidence...")
        evidence = self._gather_evidence(logs, test_code, verification_result, verification_output)
        
        # Add historical context if available
        if self.history_store:
            self._add_historical_context(test_name, evidence)
        
        # Check for intermittent failure first
        if verification_result == "passed":
            return self._intermittent_failure(test_name, evidence)
        
        # Calculate evidence-based confidence
        pattern_match = self._analyze_patterns(logs)
        
        # High confidence pattern → skip LLM
        if pattern_match and pattern_match["confidence"] > 0.90:
            self._report_progress("pattern_match", f"High confidence: {pattern_match['category']}")
            return self._create_pattern_rca(pattern_match, evidence)
        
        # Known flaky test with low pass rate
        if evidence.known_flaky or evidence.historical_pass_rate < 0.7:
            self._report_progress("flaky_detected", f"Pass rate: {evidence.historical_pass_rate:.0%}")
            return self._flaky_test_rca(test_name, evidence)
        
        # No LLM available → pattern fallback
        if not self.llm:
            self._report_progress("no_llm", "Using pattern matching only")
            if pattern_match:
                return self._create_pattern_rca(pattern_match, evidence)
            return self._fallback_rca(evidence)
        
        # Full LLM analysis with parallel Thinker+Critic
        self._report_progress("thinking", "Analyzing root cause...")
        
        # Run Thinker and Critic in parallel
        thinker_task = self._think(test_name, evidence)
        critic_task = self._prepare_critique_context(evidence)
        
        initial_rca, critique_context = await asyncio.gather(thinker_task, critic_task)
        
        self._report_progress("critiquing", "Challenging analysis...")
        critique = await self._critique(initial_rca, evidence, critique_context)
        
        self._report_progress("refining", "Finalizing RCA...")
        final_rca = await self._refine(test_name, initial_rca, critique, evidence, pattern_match)
        
        return final_rca
    
    def _gather_evidence(
        self, logs: str, test_code: str, verification_result: str, verification_output: str
    ) -> Evidence:
        """Extract comprehensive evidence from logs and code."""
        error_message = ""
        error_type = ""
        stack_trace = ""
        
        # Extract error info
        error_match = re.search(r"(?:Error|Exception):\s*(.{10,500})", logs, re.IGNORECASE)
        if error_match:
            error_message = error_match.group(0)
        
        type_match = re.search(r"(\w+Error|\w+Exception)", logs)
        if type_match:
            error_type = type_match.group(1)
        
        trace_match = re.search(r"Traceback.*?(?=\n\n|\Z)", logs, re.DOTALL)
        if trace_match:
            stack_trace = trace_match.group(0)[:800]
        
        # Extract patterns
        patterns = []
        for pattern, category, desc, _ in DEFINITIVE_PATTERNS:
            if re.search(pattern, logs, re.IGNORECASE):
                patterns.append(f"{desc} ({category})")
        
        # Analyze test code
        fixtures = []
        decorators = []
        known_flaky = False
        
        if test_code:
            # Extract fixtures
            fixture_match = re.search(r"def\s+test_\w+\s*\(([^)]+)\)", test_code)
            if fixture_match:
                fixtures = [f.strip().split(":")[0] for f in fixture_match.group(1).split(",") if f.strip()]
            
            # Extract decorators
            decorator_matches = re.findall(r"@(\w+(?:\.\w+)*(?:\([^)]*\))?)", test_code)
            decorators = decorator_matches[:10]
            
            # Check for flaky indicators
            for indicator in FLAKY_INDICATORS:
                if re.search(indicator, test_code, re.IGNORECASE):
                    known_flaky = True
                    break
        
        return Evidence(
            error_message=error_message,
            error_type=error_type,
            patterns=patterns,
            test_code=test_code[:3000] if test_code else "",
            fixtures=fixtures,
            decorators=decorators,
            stack_trace=stack_trace,
            verification_result=verification_result,
            verification_output=verification_output[:500] if verification_output else "",
            known_flaky=known_flaky,
        )
    
    def _add_historical_context(self, test_name: str, evidence: Evidence) -> None:
        """Add historical failure data to evidence."""
        try:
            history = self.history_store.get_test_history(test_name, days=14)
            if history:
                evidence.historical_failures = history.get("failure_count", 0)
                evidence.historical_pass_rate = history.get("pass_rate", 1.0)
                if evidence.historical_pass_rate < 0.8 and evidence.historical_failures > 2:
                    evidence.known_flaky = True
        except Exception as e:
            logger.debug("history_lookup_failed", error=str(e))
    
    def _analyze_patterns(self, logs: str) -> dict | None:
        """Analyze logs for known patterns with confidence scoring."""
        matches = []
        for pattern, category, desc, base_confidence in DEFINITIVE_PATTERNS:
            if re.search(pattern, logs, re.IGNORECASE):
                matches.append({
                    "category": category,
                    "description": desc,
                    "confidence": base_confidence,
                    "pattern": pattern,
                })
        
        if not matches:
            return None
        
        # Return highest confidence match
        return max(matches, key=lambda x: x["confidence"])
    
    def _create_pattern_rca(self, match: dict, evidence: Evidence) -> RCA:
        """Create RCA from pattern match with calibrated confidence."""
        category = match["category"]
        base_conf = match["confidence"]
        
        # Adjust confidence based on evidence strength
        conf = base_conf
        if len(evidence.patterns) > 2:
            conf = min(conf + 0.05, 0.98)
        if evidence.stack_trace:
            conf = min(conf + 0.03, 0.98)
        if evidence.historical_failures > 3:
            conf = max(conf - 0.1, 0.5)  # Less confident if recurring
        
        recommendations = {
            "Infrastructure Issue": "1. Check cluster health with `oc get nodes`\n2. Verify credentials and secrets\n3. Check operator status",
            "Test Automation Issue": "1. Review timeout values\n2. Add explicit waits\n3. Check test isolation",
            "Product Bug": "1. File bug report with reproduction steps\n2. Check component logs\n3. Verify configuration",
        }
        
        return RCA(
            classification=category,
            confidence=conf,
            root_cause=evidence.error_message[:200] or f"Pattern: {match['description']}",
            reasoning=f"Detected: {match['description']}. Pattern match confidence: {base_conf:.0%}",
            evidence_summary=f"Patterns: {', '.join(evidence.patterns[:3])}. Error: {evidence.error_type}",
            recommendation=recommendations.get(category, "Investigate further."),
            severity="CRITICAL" if conf > 0.9 and category == "Product Bug" else "HIGH" if category == "Product Bug" else "MEDIUM",
        )
    
    def _intermittent_failure(self, test_name: str, evidence: Evidence) -> RCA:
        """Handle test that passed on re-run."""
        return RCA(
            classification="Intermittent Failure",
            confidence=0.95,
            root_cause="Test passed on re-run, confirming intermittent behavior.",
            reasoning=f"Original error: {evidence.error_type}. Passed on verification run.",
            evidence_summary=f"Verification: PASSED. Historical flaky: {evidence.known_flaky}",
            recommendation="1. Add @pytest.mark.flaky decorator\n2. Replace sleeps with explicit waits\n3. Review resource cleanup",
            severity="LOW",
        )
    
    def _flaky_test_rca(self, test_name: str, evidence: Evidence) -> RCA:
        """Handle known flaky test."""
        return RCA(
            classification="Intermittent Failure",
            confidence=0.85,
            root_cause=f"Test has {evidence.historical_pass_rate:.0%} pass rate over recent runs.",
            reasoning=f"Historical data shows {evidence.historical_failures} failures. Known flaky indicators in code: {evidence.known_flaky}",
            evidence_summary=f"Pass rate: {evidence.historical_pass_rate:.0%}. Decorators: {', '.join(evidence.decorators[:3])}",
            recommendation="1. Investigate timing dependencies\n2. Add retry mechanism\n3. Review test isolation",
            severity="MEDIUM",
        )
    
    async def _think(self, test_name: str, evidence: Evidence) -> str:
        """Thinker: Propose initial RCA with RHOAI context."""
        system = f"""You are a senior RHOAI QE engineer. Analyze test failures concisely.

{RHOAI_CONTEXT}

Be specific about the root cause. Consider RHOAI component interactions."""

        prompt = f"""Analyze this failure:

TEST: {test_name}
ERROR: {evidence.error_type}: {evidence.error_message[:300]}
PATTERNS: {', '.join(evidence.patterns) or 'None detected'}
STACK: {evidence.stack_trace[:400] if evidence.stack_trace else 'N/A'}
DECORATORS: {', '.join(evidence.decorators[:5]) or 'None'}

Classifications:
1. Product Bug - RHOAI/ODH component defect
2. Test Automation Issue - Test code problem
3. Infrastructure Issue - Cluster/environment problem  
4. Intermittent Failure - Timing/flaky issue

Provide: classification, specific root cause, confidence %."""
        
        try:
            response = await self.llm.analyze(system, prompt)
            return self._extract_text(response)
        except Exception as e:
            logger.warning("thinker_failed", error=str(e))
            return f"Pattern analysis: {', '.join(evidence.patterns)}"
    
    async def _prepare_critique_context(self, evidence: Evidence) -> str:
        """Prepare context for critic (runs in parallel with thinker)."""
        context_parts = []
        
        if evidence.historical_failures > 0:
            context_parts.append(f"Historical: {evidence.historical_failures} failures, {evidence.historical_pass_rate:.0%} pass rate")
        
        if evidence.known_flaky:
            context_parts.append("Test has flaky indicators in code")
        
        if evidence.verification_result != "not_run":
            context_parts.append(f"Verification: {evidence.verification_result}")
        
        return " | ".join(context_parts) if context_parts else "No additional context"
    
    async def _critique(self, initial_rca: str, evidence: Evidence, context: str) -> str:
        """Critic: Challenge the analysis."""
        system = "You are a critical code reviewer. Find flaws in reasoning. Be brief."
        
        prompt = f"""Review this RCA:

{initial_rca[:500]}

Additional context: {context}

Challenge:
1. What assumptions might be wrong?
2. Alternative explanations?
3. Missing evidence?

Be rigorous but concise."""
        
        try:
            response = await self.llm.analyze(system, prompt)
            return self._extract_text(response)
        except Exception as e:
            logger.warning("critic_failed", error=str(e))
            return "Critique unavailable."
    
    async def _refine(
        self, test_name: str, initial_rca: str, critique: str, evidence: Evidence, pattern_match: dict | None
    ) -> RCA:
        """Refiner: Produce final RCA considering all evidence."""
        # Calculate evidence-based confidence
        base_confidence = 0.6
        if pattern_match:
            base_confidence = max(base_confidence, pattern_match["confidence"] - 0.1)
        if evidence.stack_trace:
            base_confidence += 0.05
        if len(evidence.patterns) > 1:
            base_confidence += 0.05
        
        system = "You are an expert QE engineer. Provide final structured analysis."
        
        prompt = f"""Finalize RCA considering initial analysis and critique.

INITIAL: {initial_rca[:400]}

CRITIQUE: {critique[:300]}

EVIDENCE:
- Error: {evidence.error_message[:200]}
- Patterns: {', '.join(evidence.patterns)}
- Suggested confidence: {base_confidence:.0%}

Format EXACTLY:
CLASSIFICATION: [Product Bug|Test Automation Issue|Infrastructure Issue|Intermittent Failure]
CONFIDENCE: [number]%
SEVERITY: [LOW|MEDIUM|HIGH|CRITICAL]
ROOT_CAUSE: [one specific sentence]
REASONING: [2 sentences max]
RECOMMENDATION: [actionable steps]"""
        
        try:
            response = await self.llm.analyze(system, prompt)
            text = self._extract_text(response)
            return self._parse_rca_response(text, evidence, base_confidence)
        except Exception as e:
            logger.warning("refiner_failed", error=str(e))
            if pattern_match:
                return self._create_pattern_rca(pattern_match, evidence)
            return self._fallback_rca(evidence)
    
    def _extract_text(self, response: Any) -> str:
        """Extract text from LLM response (handles dict or str)."""
        if isinstance(response, dict):
            return response.get("summary") or response.get("raw") or str(response)
        return str(response)
    
    def _parse_rca_response(self, response: str, evidence: Evidence, suggested_conf: float) -> RCA:
        """Parse LLM response with robust extraction."""
        def extract(pattern: str, default: str) -> str:
            match = re.search(pattern, response, re.IGNORECASE | re.DOTALL)
            if match:
                return match.group(1).strip()
            return default
        
        # Try structured format first
        classification = extract(r"CLASSIFICATION:\s*([^\n]+)", "")
        if not classification:
            # Try markdown format
            classification = extract(r"\*\*Classification:?\*\*\s*([^\n]+)", "")
        if not classification:
            # Infer from content
            if "infrastructure" in response.lower():
                classification = "Infrastructure Issue"
            elif "product bug" in response.lower() or "bug" in response.lower():
                classification = "Product Bug"
            elif "automation" in response.lower() or "test" in response.lower():
                classification = "Test Automation Issue"
            else:
                classification = "Infrastructure Issue"
        
        # Normalize classification
        valid = ["Product Bug", "Test Automation Issue", "Infrastructure Issue", "Intermittent Failure"]
        classification = next((v for v in valid if v.lower() in classification.lower()), classification)
        if classification not in valid:
            classification = "Infrastructure Issue"
        
        # Extract confidence
        conf_match = re.search(r"(?:CONFIDENCE|confidence)[:\s]*(\d+)", response)
        if conf_match:
            confidence = min(int(conf_match.group(1)) / 100, 0.98)
        else:
            confidence = suggested_conf
        
        # Extract other fields
        severity = extract(r"SEVERITY:\s*(\w+)", "MEDIUM").upper()
        if severity not in ["LOW", "MEDIUM", "HIGH", "CRITICAL"]:
            severity = "MEDIUM"
        
        root_cause = extract(r"ROOT_CAUSE:\s*([^\n]+)", "")
        if not root_cause:
            root_cause = extract(r"\*\*Root Cause:?\*\*\s*([^\n]+)", evidence.error_message[:200])
        
        reasoning = extract(r"REASONING:\s*(.+?)(?=RECOMMENDATION|$)", "")
        if not reasoning:
            reasoning = extract(r"\*\*(?:Why|Reasoning):?\*\*\s*(.+?)(?=\*\*|$)", "Based on error analysis.")
        
        recommendation = extract(r"RECOMMENDATION:\s*(.+?)$", "")
        if not recommendation:
            recommendation = extract(r"\*\*Recommendation:?\*\*\s*(.+?)(?=\*\*|$)", "Investigate further.")
        
        return RCA(
            classification=classification,
            confidence=confidence,
            root_cause=root_cause[:400] or evidence.error_message[:200],
            reasoning=reasoning[:500] or "Based on error patterns and evidence.",
            evidence_summary=f"Error: {evidence.error_type}. Patterns: {', '.join(evidence.patterns[:3])}",
            recommendation=recommendation[:500] or "Review logs and investigate.",
            severity=severity,
        )
    
    def _fallback_rca(self, evidence: Evidence) -> RCA:
        """Fallback when all else fails."""
        if evidence.patterns:
            for p in evidence.patterns:
                if "Infrastructure" in p:
                    return RCA(
                        classification="Infrastructure Issue",
                        confidence=0.6,
                        root_cause=evidence.error_message[:200] or "Infrastructure-related failure",
                        reasoning=f"Pattern detected: {p}",
                        evidence_summary=f"Patterns: {', '.join(evidence.patterns)}",
                        recommendation="Check cluster health and operator status.",
                        severity="MEDIUM",
                    )
        
        return RCA(
            classification="Infrastructure Issue",
            confidence=0.4,
            root_cause=evidence.error_message[:200] or "Unknown failure",
            reasoning="Unable to determine root cause with high confidence.",
            evidence_summary=f"Error type: {evidence.error_type}",
            recommendation="Manual investigation required.",
            severity="MEDIUM",
        )


async def batch_investigate(
    investigator: RCAInvestigator,
    failures: list[dict],
    max_concurrent: int = 3,
) -> list[tuple[str, RCA]]:
    """Investigate multiple failures with smart batching."""
    # Group by error signature
    signatures: dict[str, list[dict]] = {}
    for f in failures:
        sig = get_error_signature(f.get("logs", ""))
        if sig not in signatures:
            signatures[sig] = []
        signatures[sig].append(f)
    
    results = []
    semaphore = asyncio.Semaphore(max_concurrent)
    
    async def investigate_one(failure: dict, reuse_rca: RCA | None = None) -> tuple[str, RCA]:
        async with semaphore:
            if reuse_rca:
                # Reuse RCA for same signature, just update test name
                return (failure["name"], reuse_rca)
            
            rca = await investigator.investigate(
                test_name=failure["name"],
                logs=failure.get("logs", ""),
                test_code=failure.get("test_code", ""),
            )
            return (failure["name"], rca)
    
    # Process each signature group
    for sig, group in signatures.items():
        if len(group) == 1:
            result = await investigate_one(group[0])
            results.append(result)
        else:
            # Investigate first, reuse for others
            first_result = await investigate_one(group[0])
            results.append(first_result)
            
            # Reuse for similar failures
            for f in group[1:]:
                results.append((f["name"], first_result[1]))
                logger.debug("reusing_rca", signature=sig[:8], test=f["name"][:30])
    
    return results


def get_error_signature(logs: str) -> str:
    """Get unique signature for error grouping."""
    patterns = [
        r"(\w+Error|\w+Exception)[:\s]+(.{10,100})",
        r"(CrashLoopBackOff|ImagePullBackOff|OOMKilled)",
        r"(AccessDenied|InvalidAccessKeyId)",
        r"(CRD.*not.*found)",
        r"(InferenceService.*not.*ready)",
    ]
    
    for pattern in patterns:
        match = re.search(pattern, logs, re.IGNORECASE)
        if match:
            return hashlib.md5(match.group(0)[:100].encode()).hexdigest()[:12]
    
    return hashlib.md5(logs[:300].encode()).hexdigest()[:12]
